services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hc_fulfillment_sqlserver
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - hc_fulfillment_mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q 'select 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  hc_fulfillment_mssql_data:
