[project]
name = "project1-hc-fulfillment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=3.0.3",
    "pendulum>=3.2.0",
    "pymssql>=2.3.4",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "notebook>=7.5.7",
]
